### ISSUE TITLE
missing code for observable

### ISSUE THREAD

**Issue by lovely1980** [minuz/FirebaseSample#1]
hi this is a nice code, i am developing an app based on this code.but i am stuck at adding an observable to get say vehicle detail in this code. Please help.

**Comment by minuz** [comment]
Hi @lovely1980,
Can you please point me where exactly you are having an issue?

**Comment by lovely1980** [comment]
hi @minuz  thanks for replying
i am trying to use this code in ionic app with navcontroller instead of router, it works correctly but how can i subscribe to user and achieve the following structure in utils,

export class ApiUrl {
    public static car = `/userProfile/${user.uid}/cars`;
    public static bike = `/userProfile/${user.uid}/bikes`;
    public static motorcycle = `/userProfile/${user.uid}/motorcycles`;
    public static truck = `/userProfile/${user.uid}/trucks`;
}
and for object observable say in vehicle detail page
export class ApiUrl {
    public static car = `/userProfile/${user.uid}/cars/${carId}`;
    public static bike = `/userProfile/${user.uid}/bikes/${bikeId}`;
    public static motorcycle = `/userProfile/${user.uid}/motorcycles/${motorcycleId}`;
    public static truck = `/userProfile/${user.uid}/trucks/${truckId}`;
}

**Comment by minuz** [comment]
Hi @lovely1980,

If I understood correctly, you want to subscribe to an observable from those collections right?
so on the `VehiclesService `, you have the REST verbs where you send the url and the query.

On the component you inject the service and then on the load method, you do something like:

`this.service.Get<Car>(ApiUrl.car).subscribe(data => this.cars = data);` 

Is that what you are looking for?

**Comment by lovely1980** [comment]
hi @minuz ,
that's exactly what i am looking for, but i don't know how to write code inside switch statement and use it in other pages. it would be great if u could update your whole code this way by subscribing to user so that we can get userwise vehiclelist.
Thanks for your kind support.

**Comment by lovely1980** [comment]
hi @minuz ,
plz update this code for angularfire v5

**Comment by minuz** [comment]
Hi @lovely1980, 

I'm a bit tight on time atm. I'll see what I can do...
However, it's more likely I'll only have time to do this angular upgrade next week...
And in regards to your other request, the switch is a normal javascript switch case statements, however, the sample data model does not cater for userId and that's probably why it's not working for you.

To have this working, you will need to change the data model so every time you add a vehicle, you add to the user's collection rather than a global collection as it is.
I'll not perform this change as the purpose of this sample is simple to demonstrate the basic integration with Firebase.

Maybe in the future when I have a bit more time I'll add multi-tenancy to the data-model, but in the mean time, you can research Firebase multi-tenancy data model and modify for your purposes.

Also, in that case, you might want something more robust than the switch. Probably a factory pattern would be more appropriate.

**Comment by lovely1980** [comment]
thanks for ur suggestion @minuz , I will eagerly wait for ur upgrade to af5

**Comment by minuz** [comment]
Hi @lovely1980, feel free to pull master again. Did the upgrade to Angular 5. Enjoy!

**Comment by lovely1980** [comment]
thanks @minuz ,i think something is missing, cant access link 'Lucsan Technical Assessment' on the 1st page

**Comment by minuz** [comment]
@lovely1980 can you please check if the issue you were seeing is fixed?

**Comment by lovely1980** [comment]
thanks @minuz 
i m having another issue while implementing multi path update in
createVehicle() {
        let values = this.formGroup.value;
        this.vehicleService.Post(this.apiUrl, values)
            .subscribe(res => this.onvehicleSaved(res));
    } 

i am trying to use the following code but no success
              createPostService(userId: any, postBody: any){ 
  	 // A post entry.
           var postData = {
                  uid: userId,
                     body: postBody
                      };
          // Get a key for a new Post.
             var newPostKey = this.postsNode.push().key;
           // Write the new post's data simultaneously in the posts list and the user's post list.
           var updatePath = {};
               updatePath['/posts/' + newPostKey] = postData;
           updatePath['/user-posts/' +userId+"/"+ newPostKey] = postData;
             //update both tables simultaneously
              return this.fireRef.update(updatePath);	
             }
             // this.userNode = firebase.database().ref('users');
  	    //  this.postsNode = firebase.database().ref('posts');
  	   //  this.fireRef = firebase.database().ref();


getting error:
Property 'key' does not exist on type 'Observable<{}[]>'
in line:
var newPostKey = this.vehiclesService.Post(this.apiUrl).key;

**Comment by lovely1980** [comment]
hi @minuz  can you please update your code for firestore.
thanks

**Comment by minuz** [comment]
@lovely1980 I updated the solution to use firestore. However, I think you should read more the docs and play with it yourself. It super simple and I wanted to test it myself. Do not expect me to keep performing this sort of upgrades in the future.
